# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tar2rubyscript}
  s.version = "0.4.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Erik Veenstra", "Ryan Booker", "Ed Wagner"]
  s.date = %q{2009-10-06}
  s.default_executable = %q{tar2rubyscript}
  s.description = %q{Compile ruby applications into a single ruby script file for easy deployment. A simple update of http://www.erikveen.dds.nl/tar2rubyscript}
  s.email = %q{ed@edwagner.org}
  s.executables = ["tar2rubyscript"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "SUMMARY",
     "VERSION",
     "bin/empty",
     "bin/tar2rubyscript",
     "lib/empty",
     "realstuff.rb"
  ]
  s.homepage = %q{http://github.com/edwagner/tar2rubyscript}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{A Tool for Distributing Ruby Applications}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
